### PR TITLE
Detect harts that can't boot Linux instead of hard-coding them

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
This checks to see if a hart can't boot Linux by looking for a
compatible "mmu-type" field.  If the hart can't boot Linux, then bbl
masks it off.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
@terpstra I just found this sitting on my computer somewhere, but it boots in spike... :)

**Comment by terpstra** [comment]
We should change spike to put something indicating HTIF into DTS.

**Comment by terpstra** [comment]
As for this PR, does it also boot the FPGAs? If so, let's merge it! 👍

**Comment by palmer-dabbelt** [comment]
That's next on the list, but at least BBL tries the UART first.

**Comment by palmer-dabbelt** [comment]
I haven't tried it on an FPGA...

**Comment by palmer-dabbelt** [comment]
@aswaterman I just bumbled my way through https://github.com/riscv/riscv-pk/pull/67/commits/27498013ad7684a5f22a99790ac29badea205a3f without checking to see if this still results in sane FP emulation code.  Does it look OK?

**Comment by palmer-dabbelt** [comment]
This boots on our U54-MC FPGA.  I can't get a DHCP lease, but it doesn't seem like it's related to this...

**Comment by aswaterman** [comment]
It looks OK but you should try it out.  If you compile bbl with -march=rv64imac, and use spike --isa=rv64imac, then a floating-point-enabled Linux userland should still work correctly.

**Pull request merged**
