### PR TITLE
Add Hwacha support.

### PR DESCRIPTION
**Pull request by lluixhi**
This is mostly stuff ripped out of esp-tests.

It appears to work, but as it seems there are other bugs in my test code, I'm not 100% sure.

### CODE REVIEW

**Comment by aswaterman** [comment]
Since Hwacha is a non-standard extension, this should be maintained on a branch rather than merged into pk.

**Comment by lluixhi** [comment]
@aswaterman 
Will github allow me to create pull requests for a branch that does not yet exist?
Or will you merge these changes into a `hwacha` branch?

**Comment by aswaterman** [comment]
I'd like @colinschmidt to weigh in on how to maintain it, since he's in charge of esp-tools.

**Comment by palmer-dabbelt** [comment]
Thanks, but Hwacha is somewhat defunct and the tools are not maintained.

**Comment by colinschmidt** [comment]
Sorry was on vacation. I don't think it makes sense to upstream this.

**Pull request closed without merging**
